"use client";
import { useAppDispatch, useAppSelector } from "@/store";
import {
  decreaseCount,
  increaseCount,
  initCounter,
} from "@/store/counter/counterSlice";
import React, { useEffect } from "react";

interface CartCounterProps {
  value?: number;
}

// Generated by https://quicktype.io
export interface CounterResponse {
  count: number;
}

const getApiCounter = async () => {
  const data = await fetch("/api/counter").then((res) => res.json());
  console.log(data);
  return data;
};

export const CartCounter = ({ value = 0 }: CartCounterProps) => {
  const dispatch = useAppDispatch();
  const count = useAppSelector((state) => state.counter.count);

  // useEffect(() => {
  //   dispatch(initCounter(value));
  // }, []);
  useEffect(() => {
    getApiCounter().then(({ count }) => dispatch(initCounter(count)));
  }, []);

  return (
    <>
      <span>Products in the cart</span>
      <span className="text-9xl">{count}</span>

      <div className="flex">
        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
          onClick={() => dispatch(decreaseCount())}
        >
          -1
        </button>
        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
          onClick={() => dispatch(increaseCount())}
        >
          +1
        </button>
      </div>
    </>
  );
};
